#Diabeted prediction Mini Project - SmartKnower

In [ ]:
import pandas as pd

In [ ]:
#load the dataset
df = pd.read_csv('/content/drive/MyDrive/MINI PROJECT(Diabetes Prediction)/pima-diabetes.csv', header=None)
df.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [ ]:
from numpy import loadtxt
import numpy as np
from keras.utils import np_utils
from sklearn.preprocessing import scale
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
df.columns=['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThiness', 'Inuslin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Class']
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Class
0            6      148             72  ...                     0.627   50      1
1            1       85             66  ...                     0.351   31      0
2            8      183             64  ...                     0.672   32      1
3            1       89             66  ...                     0.167   21      0
4            0      137             40  ...                     2.288   33      1

[5 rows x 9 columns]

In [ ]:
# load the dataset
dataset = loadtxt('/content/drive/MyDrive/MINI PROJECT(Diabetes Prediction)/pima-diabetes.csv', delimiter=',')
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

Split data into training and testing

In [ ]:
#split into input-x and output-y variables
X = dataset[:,0:8]
y = dataset[:,8]

In [ ]:
X_scaled = scale(X) 
print('Scale - X :\n', X_scaled)

Scale - X :
 [[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]


In [ ]:
# Split dataset into 'train' & 'test' sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.33, random_state=42)

In [ ]:
y_train = np_utils.to_categorical(y_train)

In [ ]:
print('Train-Y Encoded:\n', y_train)

Train-Y Encoded:
 [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [1. 0.]]


In [ ]:
#Keras model RELU
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(2, activation='sigmoid'))

In [ ]:
#Compilation keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# fit the keras model on the dataset
history = model.fit(X_train, y_train, validation_split=0.33, epochs=150, batch_size=10)

Epoch 1/150
35/35 [==============================] - 1s 7ms/step - loss: 0.6930 - accuracy: 0.5494 - val_loss: 0.6946 - val_accuracy: 0.5647
Epoch 2/150
35/35 [==============================] - 0s 3ms/step - loss: 0.6559 - accuracy: 0.7151 - val_loss: 0.6692 - val_accuracy: 0.6765
Epoch 3/150
35/35 [==============================] - 0s 4ms/step - loss: 0.6278 - accuracy: 0.7471 - val_loss: 0.6453 - val_accuracy: 0.7118
Epoch 4/150
35/35 [==============================] - 0s 3ms/step - loss: 0.6009 - accuracy: 0.7558 - val_loss: 0.6273 - val_accuracy: 0.7235
Epoch 5/150
35/35 [==============================] - 0s 3ms/step - loss: 0.5766 - accuracy: 0.7645 - val_loss: 0.6106 - val_accuracy: 0.7235
Epoch 6/150
35/35 [==============================] - 0s 3ms/step - loss: 0.5527 - accuracy: 0.7703 - val_loss: 0.5933 - val_accuracy: 0.7412
Epoch 7/150
35/35 [==============================] - 0s 3ms/step - loss: 0.5325 - accuracy: 0.7878 - val_loss: 0.5788 - val_accuracy: 0.7176
Epoch 8/150
3

Predict for Testing Data

In [ ]:
#Evaluate
_, accuracy = model.evaluate(X_train, y_train)
print('Accuracy: %.2f' % (accuracy*100))

17/17 [==============================] - 0s 2ms/step - loss: 0.3851 - accuracy: 0.8405
Accuracy: 84.05


Prediction

In [ ]:
#class prediction with the model
predictions = np.argmax(model.predict(X_test), axis=-1)

# summarize the 1st  -  5 cases
for i in range(10):
    print('%s => %d (expected %d)' % (X_test[i].tolist(), predictions[i], y[i])) 


[0.6399472601593618, -0.7165334717264664, -0.5741277459136239, 0.7818138030884967, 0.956859653030945, 0.2547804694892943, -0.1264714020604746, 0.8303811324799336] => 0 (expected 1)
[-0.5479185907225473, -0.2783734371474431, 0.30473400231574344, 0.7190857419965655, -0.6928905722954664, 0.47054318659717476, -0.9781448690748636, -1.0415494364835027] => 0 (expected 0)
[-0.5479185907225473, -0.4035620184557355, -0.2639412465385531, -1.2882122129452327, -0.6928905722954664, -0.1513611156549505, -0.9479436823013037, -1.0415494364835027] => 0 (expected 1)
[1.233880185600316, -0.4348591637828086, 0.5632227517949692, -1.2882122129452327, -0.6928905722954664, -0.9382604368719248, 1.1600991544931767, 0.06459135426761878] => 0 (expected 0)
[0.9369137228798391, 0.4727580507023112, 1.0802002507534205, -1.2882122129452327, -0.6928905722954664, -0.26558843647676966, -0.7908975110787921, 1.4259954044228451] => 0 (expected 1)
[0.6399472601593618, -0.560047745091101, 0.149640752628208, 0.7190857419965655,

In [ ]:
y_pred = model.predict(X_test)

y_pred = np.argmax(y_pred, axis=1) 

print("Prediction = ", accuracy_score(y_test, y_pred))

Prediction =  0.7519685039370079


In [ ]:
print(model.metrics_names)
print("\n")
print(history.history.keys())

['loss', 'accuracy']


dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])


In [ ]:
###accuracy(confusion_matrix):
    #diagonal_sum = confusion_matrix.trace()
    #sum_of_all_elements = confusion_matrix.sum()
    #return diagonal_sum / sum_of_all_elements ###

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[136,  32],
       [ 31,  55]])